Repository Matrix-Shop-Project/frontend, pull requests merged in 2022-08, with the labels that each got.

#136 Vens Login Authentication, react-toastify install
  package-lock.json
  package.json
  src/Components/Login/Login.js
  src/Components/Pages/Products.js
  src/Context/UserContext.js
Labels: bug, enhancement

#137 Dev Login Authentication, react-toastify install
  package-lock.json
  package.json
  src/Components/Login/Login.js
  src/Components/Pages/Products.js
  src/Context/UserContext.js
Labels: enhancement

#138 Paymend add und style fix, responsive
  package-lock.json
  package.json
  src/App.js
  src/Components/Chat/ChatApp.js
  src/Components/NavBar/CategoryNav.js
  src/Components/NavBar/Header.js
  src/Components/Pages/Home.js
  src/Components/Products/CartComponent.js
  src/Components/Products/Payment.js
  src/Components/Products/ProgressBar.js
  src/Components/Products/Shipping.js
  src/Components/Products/Warenkorb.js
  src/Components/Products/cart.js
  src/sass/Chat.scss
  src/sass/NavCategory.scss
  src/sass/ShoppingCart.scss
Labels: enhancement

#141 Dev
  package-lock.json
  package.json
  src/Components/Carousel/Carousel.js
Labels: bug, enhancement

#147 Dev
  src/Components/Products/Payment.js
Labels: bug

#148 Dev
  src/Components/Products/Payment.js
Labels: bug

#149 Über uns erstellt
  public/assets/image/user/orhan.jpg
  public/assets/image/user/vens.jpg
  src/App.js
  src/Components/NavBar/SidebarUserData.js
  src/Components/Pages/About.js
  src/Components/Pages/Image/orhan.jpg
  src/Components/Pages/Image/vens.jpg
Labels: enhancement

#151 über orhan beschreibung
  src/Components/Pages/About.js
Labels: enhancement

#152 Dev über orhan beschreibung
  src/Components/Pages/About.js
Labels: enhancement

#153 Bay me Caffe button
  package-lock.json
  package.json
  src/Components/Pages/About.js
Labels: enhancement

#154 Dev Bay me Caffe button
  package-lock.json
  package.json
  src/Components/Pages/About.js
Labels: enhancement

#155 Dev
  src/Components/Pages/About.js
  src/Components/Products/cart.js
Labels: bug, enhancement

#156 Vens comment
  src/Components/Login/Register.js
  src/Components/Pages/Contact.js
  src/Components/Pages/Impressum.js
  src/Components/Products/Admin/createproduct.js
  src/Components/Products/Cart/CartItem.js
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/Cart/cartSlice.js
  src/Components/Products/Cart/useLocalStorage.js
  src/Components/Products/ComponentShoppingCart copy.js
  src/redux/action/commentsAction.js
  src/redux/action/products.js
  src/redux/reducers/commentsReducers.js
  src/redux/reducers/createproduct.js
Labels: bug, enhancement

#158 Final Advent 17.08.2022
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/cart.js
Labels: bug

#159 Final Advent 17.08.2022
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/cart.js
Labels: bug
