Repository Matrix-Shop-Project/frontend, pull requests merged in 2022-07, with the labels that each got.

#49 MarginTop delete home.js
  src/sass/Pages.scss
Labels: enhancement

#52 Vens chat mit neu server linked
  src/Components/Chat/ChatApp.js
Labels: enhancement

#55 Vens chat
  src/Components/Chat/ChatApp.js
Labels: bug, enhancement

#56 Dev
  package-lock.json
  src/App.js
  src/Components/Chat/ChatApp.js
  src/Components/Pages/ShoppingCart.js
  src/Components/Products/ProductCart.js
  src/Components/Products/ShoopingCart.js
Labels: bug

#59 Dev
  src/Components/Chat/ChatApp.js
Labels: bug

#60 Product context
  src/Components/Products/Products.js
  src/Components/Products/ProductsCart.js
  src/Context/ProductContext.js
  src/index.js
Labels: enhancement

#61 Product context
  src/Components/Products/Products.js
  src/Components/Products/ProductsCart.js
  src/Context/ProductContext.js
  src/index.js
Labels: enhancement

#63 Admin context axios fix
  src/Components/Products/Products.js
  src/Context/AdminContext.js
  src/Context/ProductContext.js
  src/index.js
Labels: bug

#65 Vens header footer
  src/sass/Pages.scss
Labels: bug

#70 Dev 3
  src/Components/Carousel/Carousel.js
Labels: bug

#73 Orhan added product card and shopping card
  package-lock.json
  package.json
  src/Components/Pages/ShoppingCart.js
  src/Components/Products/ProductCart.js
  src/Components/Products/ProductsCart.js
  src/Components/Products/ShoopingCart.js
  src/Components/Products/ShoppingCartItem.js
  src/index.js
Labels: enhancement

#77 Orhan product cart2
  src/Components/Chat/ChatApp.js
  src/Components/Pages/Account.js
  src/Components/Pages/Category.js
  src/Components/Pages/Products.js
  src/Components/Products/ComponentShoppingCart.js
  src/Components/Products/ProductCart.js
  src/Components/Products/Products.js
  src/Components/Products/ProductsCart.js
  src/Context/CartContext.js
  src/sass/Products.scss
Labels: bug, enhancement

#78 Dev
  src/Components/Chat/ChatApp.js
  src/Components/Pages/Account.js
  src/Components/Pages/Category.js
  src/Components/Pages/Products.js
  src/Components/Products/ComponentShoppingCart.js
  src/Components/Products/ProductCart.js
  src/Components/Products/Products.js
  src/Components/Products/ProductsCart.js
  src/Context/CartContext.js
  src/sass/Products.scss
Labels: enhancement

#79 orhan added product cart fix
  src/Components/Chat/ChatApp.js
  src/Components/Products/ProductCart.js
  src/Components/Products/ProductsCart.js
Labels: bug

#83 Bei login prüft User, wenn Admin ist, dann ist zur Adminseite navigiert. Normal User navigiert zu Userseite
  src/Components/Login/Login.js
  src/Context/UserContext.js
Labels: bug, enhancement

#84 Admin prüfen
  src/Components/Login/Login.js
  src/Context/UserContext.js
Labels: enhancement

#85 Vens admin page bog fix decoded = jwt_decode(token);
  src/Components/Login/Login.js
  src/Context/UserContext.js
  src/index.js
Labels: bug

#86 admin, login page bug fix decoded = jwt_decode(token);
  src/Components/Login/Login.js
  src/Context/UserContext.js
  src/index.js
Labels: bug

#87 Orhan product cart modifiert
  src/App.js
  src/Components/Bitcoin/Bitcoin.js
  src/Components/NavBar/CategoryNav.js
  src/Components/Pages/BitcoinPage.js
  src/Components/Products/ProductsCart.js
Labels: bug

#88 Vens loginform
  package-lock.json
  package.json
  src/Components/Login/Login.js
  src/Context/UserContext.js
Labels: bug, enhancement

#91 Onli admin gesichert
  src/Components/Pages/Admin.js
  src/Components/Pages/Home.js
  src/Components/Products/Admin/AdminProducts.js
  src/Components/Products/Admin/createproduct.js
  src/Components/Products/Admin/editproduct.js
  src/sass/Pages.scss
Labels: enhancement

#92 Dev only admin's
  src/Components/Pages/Admin.js
  src/Components/Pages/Home.js
  src/Components/Products/Admin/AdminProducts.js
  src/Components/Products/Admin/createproduct.js
  src/Components/Products/Admin/editproduct.js
  src/Context/UserContext.js
  src/sass/Pages.scss
Labels: bug, enhancement

#94 Login, Navigation, NavBar mit UserContext verbinden. User buttons wen…
  src/Components/NavBar/Header.js
  src/Components/NavBar/HeaderData.js
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/SidebarAdminData.js
  src/Components/NavBar/SidebarUserData.js
  src/sass/Navbar.scss
Labels: enhancement

#96 image upload base64
  src/Components/Products/Admin/createproduct.js
Labels: enhancement

#97 Dev add product image base64
  src/Components/Products/Admin/createproduct.js
Labels: enhancement

#99 Vens base64 photo
  src/Components/NavBar/Header.js
  src/Components/NavBar/HeaderData.js
  src/Components/NavBar/lottie/woman-icon.json
  src/Components/Products/Admin/createproduct.js
  src/Components/Products/Admin/editproduct.js
  src/Components/Products/Admin/table.js
  src/Components/Products/Admin/utils.js
Labels: bug, enhancement

#100 Dev photo Base64
  src/Components/NavBar/Header.js
  src/Components/NavBar/HeaderData.js
  src/Components/NavBar/lottie/woman-icon.json
  src/Components/Products/Admin/createproduct.js
  src/Components/Products/Admin/editproduct.js
  src/Components/Products/Admin/table.js
  src/Components/Products/Admin/utils.js
Labels: bug, enhancement

#101 Vens base64 photo
  src/Components/Products/Admin/createproduct.js
Labels: bug

#103 Vens cookies component erstellt
  package-lock.json
  package.json
  src/App.js
  src/Components/Cookie/Cookie.js
Labels: enhancement

#105 new bitcoin api
  src/Components/Bitcoin/Bitcoin.js
Labels: enhancement

#106 Dev
  src/Components/Bitcoin/Bitcoin.js
Labels: enhancement

#107 new carousel
  package-lock.json
  package.json
  src/Components/Carousel/Carousel.js
  src/Components/Pages/Home.js
  src/Components/Products/ProductsCart.js
  src/sass/AdminProducts.scss
  src/sass/Carousel.scss
Labels: enhancement

#109 Orhan carousel
  src/Components/Carousel/Carousel.js
Labels: enhancement

#110 Dev
  src/Components/Carousel/Carousel.js
Labels: bug, enhancement

#115 Orhan carousel gestayld
  src/Components/Carousel/Carousel.js
Labels: enhancement

#116 Dev carousel gesteilt
  src/Components/Carousel/Carousel.js
Labels: enhancement

#117 Vens productcart
  src/Components/NavBar/Header.js
  src/Components/NavBar/HeaderData.js
  src/Components/Pages/Account.js
  src/Components/Pages/Products.js
  src/Components/Pages/ShoppingCart.js
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/ComponentShoppingCart.js
  src/Components/Products/ShoopingCart.js
  src/Components/Products/ShoppingCartItem.js
  src/Components/Products/Warenkorb.js
  src/redux/action/products.js
  src/sass/ShoppingCart.scss
Labels: bug, enhancement

#119 Orhan carousel
  public/assets/image/slider/slider1-min.jpg
  public/assets/image/slider/slider2-min-min (1).jpg
  public/assets/image/slider/slider2-min-min.jpg
  public/assets/image/slider/slider2-min.jpg
  public/assets/image/slider/slider3-min (1).jpg
  public/assets/image/slider/slider3-min.jpg
  src/Components/Carousel/Carousel.js
Labels: enhancement

#120 Dev ender die carousel bilder
  public/assets/image/slider/slider1-min.jpg
  public/assets/image/slider/slider2-min-min (1).jpg
  public/assets/image/slider/slider2-min-min.jpg
  public/assets/image/slider/slider2-min.jpg
  public/assets/image/slider/slider3-min (1).jpg
  public/assets/image/slider/slider3-min.jpg
  src/Components/Carousel/Carousel.js
Labels: enhancement

#122 Warenkorb erstellt
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/Components/NavBar/CategoryNav.js
  src/Components/NavBar/Header.js
  src/Components/Products/Cart/CartItem.js
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/Cart/cartSlice.js
  src/Components/Products/Cart/index.js
  src/Components/Products/Cart/useLocalStorage.js
  src/Components/Products/ComponentShoppingCart.js
  src/Components/Products/Warenkorb.js
  src/Components/Products/store/ProductItem.js
  src/Components/Products/store/ProductsGrid.js
  src/Components/Products/store/store.js
  src/Context/CartContext.js
  src/Context/CartReducer.js
  src/Context/UserContext.js
  src/index.js
  src/redux/action/cartActions.js
  src/redux/constants/cartConstants.js
  src/redux/reducers/cartReducers.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  yarn.lock
Labels: bug, enhancement

#124 Chat function mit User add, Categorien erstellt
  package-lock.json
  package.json
  src/App.js
  src/Components/Chat/Chat.js
  src/Components/Chat/ChatApp.js
  src/Components/Pages/Admin.js
  src/Components/Pages/Home.js
  src/Components/Pages/Products.js
  src/Components/Pages/ShoppingCart.js
  src/Components/Pages/category/Damen.js
  src/Components/Pages/category/Haushalt.js
  src/Components/Pages/category/Herren.js
  src/Components/Pages/category/Kinder.js
  src/Components/Products/Admin/AdminProducts.js
  src/Components/Products/Admin/table.js
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/ComponentShoppingCart.js
  src/Components/Products/category/Damen.js
  src/Components/Products/category/Haushalt.js
  src/Components/Products/category/Herren.js
  src/Components/Products/category/Kinder.js
  src/redux/action/categoryActions.js
  src/redux/constants/categoryConstats.js
  src/redux/reducers/categoryReducers.js
  src/sass/Chat.scss
Labels: bug, enhancement

#126 Vens category
  package-lock.json
Labels: bug

#127 Dev
  package.json
  src/App.js
  src/Components/Chat/Chat.js
  src/Components/Chat/ChatApp.js
  src/Components/Pages/Admin.js
  src/Components/Pages/Home.js
  src/Components/Pages/Products.js
  src/Components/Pages/ShoppingCart.js
  src/Components/Pages/category/Damen.js
  src/Components/Pages/category/Haushalt.js
  src/Components/Pages/category/Herren.js
  src/Components/Pages/category/Kinder.js
  src/Components/Products/Admin/AdminProducts.js
  src/Components/Products/Admin/table.js
  src/Components/Products/Cart/ShoppingCart.js
  src/Components/Products/ComponentShoppingCart.js
  src/Components/Products/category/Damen.js
  src/Components/Products/category/Haushalt.js
  src/Components/Products/category/Herren.js
  src/Components/Products/category/Kinder.js
  src/redux/action/categoryActions.js
  src/redux/constants/categoryConstats.js
  src/redux/reducers/categoryReducers.js
  src/sass/Chat.scss
Labels: bug

#132 Vens categorien
  src/Components/Pages/Home.js
  src/Components/Pages/Products.js
  src/Components/Products/CartComponent.js
Labels: bug

#133 Dev
  src/Components/Pages/Home.js
  src/Components/Pages/Products.js
  src/Components/Products/CartComponent.js
Labels: bug

#134 Einlogin und Anmeldungs form fix, Footer link zum DCI, Orhan und Vens…
  src/Components/Footer/Footer.js
  src/Components/Login/Login.js
  src/Components/Login/Register.js
  src/Components/Pages/Home.js
  src/Components/Pages/Login.js
  src/Components/Pages/Products.js
  src/Components/Products/cart.js
Labels: bug, enhancement

#135 Dev Einlogin und Anmeldung fix
  src/Components/Footer/Footer.js
  src/Components/Login/Login.js
  src/Components/Login/Register.js
  src/Components/Pages/Home.js
  src/Components/Pages/Login.js
  src/Components/Pages/Products.js
  src/Components/Products/cart.js
Labels: bug, enhancement
